WIP Styles fixes for vierszy2020 collections
babajka/babajka-frontend pull request #110
Opened 2020-10-01 20:54 UTC by UladBohdan

2020-10-03 12:33 UTC, Drapegnik requested changes

2020-10-03 12:33 UTC, Drapegnik commented on components/articles/cards/ArticleCard.js
> +    rawCollection && !COLLECTIONS_HIDE_COMPLETELY[rawCollection.slug] ? rawCollection : undefined;
```suggestion
const collection = !COLLECTIONS_HIDE_COMPLETELY[rawCollection?.slug] && rawCollection;
```

2020-10-07 21:26 UTC, UladBohdan commented on components/articles/cards/ArticleCard.js
> +    rawCollection && !COLLECTIONS_HIDE_COMPLETELY[rawCollection.slug] ? rawCollection : undefined;
Done.

2020-10-12 21:46 UTC, Drapegnik approved these changes, later dismissed

2020-10-14 21:08 UTC, merged