[WIP] Diary duck
babajka/babajka-frontend pull request #17
Opened 2018-03-25 14:41 UTC by tyndria

2018-03-25 22:07 UTC, Drapegnik requested changes

2018-03-25 22:07 UTC, Drapegnik commented on components/articles/Diary.js
> +import { DiaryModel } from '../../utils/customPropTypes';
please, use absolute path

2018-03-25 22:07 UTC, Drapegnik commented on components/articles/grid/ArticlesRow.js
> +import classNames from 'classnames';
please, place it before not 3d-party import

2018-03-25 22:07 UTC, Drapegnik commented on pages/index.js
>  });
```js
const mapDispatchToProps = {
  getByDay: diaryActions.getByDay,
};
```

2018-03-25 22:07 UTC, Drapegnik commented on redux/ducks/diary.js
> +    payload: request.fetch(`${api.diary.getByDay}/${locale}/${month}/${day}`),
`request.fetch(api.diary.getByDay(locale, month, day)`

2018-03-25 22:07 UTC, Drapegnik commented on redux/ducks/diary.js
> +export default createReducer(
For reduce boilerplate in reducers I introduce [some utils](https://github.com/babajka/babajka-frontend/pull/15/files#diff-3087a1f10201c2966423b14d9250bcd0) in #16. If you want, we can merge it for sharing.

2018-03-25 22:07 UTC, Drapegnik commented on pages/index.js
> +    diary: PropTypes.shape(DiaryModel).isRequired,
in #16 I came to the fact that more convenient way is [export](https://github.com/babajka/babajka-frontend/pull/15/files#diff-76e94d767ebb316d865d41e4dc5cfb93) `Shape` & `Array` objects.

2018-03-28 11:24 UTC, UladBohdan requested changes
@tyndria could you please also add image fetching for authors and articles in this PR? It is `imageUrl` field in both cases.

2018-03-31 19:51 UTC, tyndria commented
@Drapegnik , thanks for the review!

Waiting for PR babajka/babajka-backend#23

2018-03-31 20:00 UTC, tyndria commented
@UladBohdan done

2018-03-31 20:02 UTC, UladBohdan submitted a review, later dismissed

2018-03-31 20:13 UTC, Drapegnik commented on components/articles/ArticlePreview.js
> +              <img alt={title} src={imageUrl || mockImagePath} />
please change `const mockImagePath = '/static/images/photo5.jpg';`, cause on case not root route it will be resolved as `/some/path/static...`

2018-03-31 20:15 UTC, Drapegnik commented on utils/getters.js
>  export const getLocalizedBrand = (brand, lang = 'be') => ({
`({ slug, imageUrl, names }, lang ...)`

2018-04-01 12:23 UTC, tyndria commented on components/articles/ArticlePreview.js
> +              <img alt={title} src={imageUrl || mockImagePath} />
I see, done!

2018-04-01 13:21 UTC, Drapegnik approved these changes

2018-04-01 13:22 UTC, merged

2018-04-02 13:16 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [main page frontend](https://trello.com/c/ck2rjG3z/51-main-page-frontend)