Very important fixes. Getting ready to launch!
babajka/babajka-frontend pull request #37
Opened 2018-07-25 07:51 UTC by UladBohdan

* Dante2 is updated so that "kek" issue is gone

2018-07-25 07:52 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [images are not rendered properly in the Editor: add an image to article -> save -> back to editor (it's broken) -> back to article page (it's ok)](https://trello.com/c/o9e3rUgd/249-images-are-not-rendered-properly-in-the-editor-add-an-image-to-article-save-back-to-editor-its-broken-back-to-article-page-its-o)

2018-07-26 11:40 UTC, Drapegnik submitted a review, later dismissed

2018-07-27 00:54 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [save / remove / open buttons under the Editor are too close to the footer, looks awful](https://trello.com/c/v133CT4V/251-save-remove-open-buttons-under-the-editor-are-too-close-to-the-footer-looks-awful)

2018-07-27 00:54 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [save / remove / open buttons under the Editor are too close to the footer, looks awful](https://trello.com/c/v133CT4V/251-save-remove-open-buttons-under-the-editor-are-too-close-to-the-footer-looks-awful)

2018-07-28 22:28 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [to add 'remove article' button on Frontend](https://trello.com/c/ryufaBgF/219-to-add-remove-article-button-on-frontend)

2018-07-29 11:41 UTC, tyndria commented
![](https://github.trello.services/images/mini-trello-icon.png) [Chrome tries to autocomplete videoUrl field with postal index, why?](https://trello.com/c/Cnjd4AyE/248-chrome-tries-to-autocomplete-videourl-field-with-postal-index-why)

2018-07-29 15:25 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [to implement 404 page on Frontend](https://trello.com/c/J30dI2Ko/181-to-implement-404-page-on-frontend)

2018-08-01 20:56 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [google analytics script repeating bug](https://trello.com/c/xb03e8Lq/262-google-analytics-script-repeating-bug)

2018-08-05 09:04 UTC, Drapegnik requested changes

2018-08-05 09:04 UTC, Drapegnik commented on components/articles/PublicArticle/PublicArticle.js
> +import _ from 'lodash';
please use `import foo from 'lodash/foo'` [method](https://stackoverflow.com/questions/35250500/correct-way-to-import-lodash)

2018-08-05 09:15 UTC, Drapegnik commented on components/articles/PublicArticle/PublicArticle.js
> +import _ from 'lodash';
one line - `+527.73 KB`:

<img width="698" alt="screen shot 2018-08-05 at 12 12 41" src="https://user-images.githubusercontent.com/11758660/43684453-f6be61a4-98a8-11e8-9d5c-cf3d2ad1841b.png"><img width="644" alt="screen shot 2018-08-05 at 12 11 29" src="https://user-images.githubusercontent.com/11758660/43684454-f8649f32-98a8-11e8-8ad2-a3e2c4f17dd0.png">

2018-08-05 13:02 UTC, Drapegnik approved these changes

2018-08-05 13:05 UTC, merged