Login page
babajka/babajka-frontend pull request #4
Opened 2017-10-28 20:58 UTC by Drapegnik

2017-10-30 10:32 UTC, Fusionqq commented
Maybe make sense doing login button smaller and with non-transparent background?

2017-10-30 10:33 UTC, Fusionqq submitted a review, later dismissed

2017-10-30 12:44 UTC, UladBohdan commented
Not sure what to test here.
But infinite pending looks weird: it spins too fast, and not clear why we need two spinners (or even three when it's a signup mode) - what if we add one on "Паехалі" button?

And remove letter "д" in "Пацвердзіце" word plz.

2017-10-30 12:45 UTC, UladBohdan requested changes
Not sure what to test here.
But infinite pending looks weird: it spins too fast, and not clear why we need two spinners (or even three when it's a signup mode) - what if we add one on "Паехалі" button?

And remove letter "д" in "Пацвердзіце" word plz.

2017-10-30 12:57 UTC, Drapegnik commented
@UladBohdan, redirect issues to `@babajka/markup` team.

2017-10-30 13:02 UTC, UladBohdan requested changes
But you're manually reapplying all html-markup changes. Redirecting to markup team won't help.

2017-10-30 13:02 UTC, UladBohdan commented on components/auth/LoginForm.js
> +            <input className="input password-input" type="password" placeholder="Падцвердзіце пароль" />
Even if it's fixed in markup, here we still have "д" mistype. Should be fixed both here and in markup.

2017-11-18 14:54 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [login page frontend](https://trello.com/c/VtDqIPmE/66-login-page-frontend)

2017-11-18 19:14 UTC, UladBohdan submitted a review, later dismissed

2017-11-18 22:27 UTC, UladBohdan commented
Not sure why package-lock.json got updated.

2017-11-26 16:12 UTC, UladBohdan commented
I've created a new account and was able to log into it. Awesome!

Some minor questions/suggestions:
1. what's the plan about "forgot password" button?
2. can you change the tab order so that on login after I've filled in the email field and press tab - I'm on the password field? that would be much more convenient. Now there's this intermediate "forgot password" position.
3. it doesn't save the session, is that fine for now?
4. what about reseting all warning once I switch between login and signup? It's a bit weird: I put the cursor into the "email" field, type nothing, escape the cursor from the field - the warning "bad email" appears - than I switch into the signup mode - but the warning it still present.

And it seems to me there's a rule: if user failed to login, we NEVER indicate if email is incorrect or passport doesn't match. That gives too much information. We must return "failed to login" error in any case. That's a fix for both backend and frontend.

2017-11-26 20:34 UTC, Drapegnik commented
@UladBohdan:
1. hide `forgot password` btn for now, not urgent feature
2. in future can be fixed with [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
3. there is [`task`](https://trello.com/c/HGRitZDA/76-auth-cookies-bugs) for it
4. fixed it: clear set `touched: false` for empty fields when mode switched
5. `failed to login` should be fixed on backend

2017-11-26 20:35 UTC, UladBohdan approved these changes

2017-11-26 20:48 UTC, merged