Use Yup for validation
babajka/babajka-frontend pull request #43
Opened 2018-10-27 14:32 UTC by andemerie

2018-10-28 12:15 UTC, Drapegnik commented
### develop
![develop-client](https://user-images.githubusercontent.com/11758660/47615692-348e0280-dac3-11e8-8a3a-b1e75560e681.png)

### vd-login-form
![vd-login-form-client](https://user-images.githubusercontent.com/11758660/47615693-348e0280-dac3-11e8-9d12-f4baadab73b3.png)

2018-10-28 12:30 UTC, Drapegnik requested changes

2018-10-28 12:30 UTC, Drapegnik commented on components/auth/LoginForm.js
> +import * as Yup from 'yup';
please, use `import { string, object } from 'yup';`

2018-10-28 12:30 UTC, Drapegnik commented on components/auth/LoginForm.js
> +        ? schema.oneOf([Yup.required('forms.required').ref('password')], 'auth.passwordsNotEqual')
is it possible somehow omit this ternary?

2018-10-28 12:36 UTC, Drapegnik commented
lets try [spected](https://github.com/25th-floor/spected):
```
  package        size      minified  gzipped
  spected@0.7.0  72.67 KB  12.42 KB  3.3 KB
```

[Simple React form validation with Formik, Yup and/or Spected](https://itnext.io/simple-react-form-validation-with-formik-yup-and-or-spected-206ebe9e7dcc)

2018-12-11 09:14 UTC, UladBohdan commented
@andemerie what about this PR ?

2019-01-17 10:15 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor forms validation](https://trello.com/c/fvZqHXou/280-refactor-forms-validation)

2019-09-21 17:36 UTC, UladBohdan commented
I suggest to wait until Oct 27, 2019
Then to celebrate that
And then to close this PR

2019-12-28 17:51 UTC, closed without merging