New Layout
babajka/babajka-frontend pull request #53
Opened 2019-03-18 11:22 UTC by Drapegnik

2019-03-18 23:24 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [new layout frontend](https://trello.com/c/9mufuFnz/355-new-layout-frontend)

2019-03-20 12:04 UTC, UladBohdan approved these changes

2019-03-20 12:45 UTC, UladBohdan requested changes

2019-03-20 12:45 UTC, UladBohdan commented on components/common/LinkWraper.js
> +    {children}
I think we need to wrap `{children}` here with `<span></span>`
Check this out: https://github.com/babajka/babajka-markup/blob/develop/src/kit/link/link.ejs#L6

Also: what if `children` is not text? In markup it's explicitly marked as text

2019-03-20 21:56 UTC, UladBohdan approved these changes

2019-03-20 21:58 UTC, merged