task(article): create base article layout
babajka/babajka-frontend pull request #64
Opened 2019-07-09 21:13 UTC by andemerie

2019-07-09 21:39 UTC, Drapegnik requested changes
Could you, please, remove `pages/legacy/article` and unused `PublicArticle` components?

2019-07-09 21:39 UTC, Drapegnik commented on pages/article.js
> +    const { description, covers, tags, title, subtitle, imagePreviewUrl } = article;
```suggestion
    const { article: { description, covers, tags, title, subtitle, imagePreviewUrl } } = this.props;
```

2019-07-09 21:43 UTC, Drapegnik commented on pages/article.js
> +            <ShareButtons />
please, implement **sharing**, like in `ShareToButton.js`

2019-07-09 21:44 UTC, Drapegnik commented on pages/article.js
> +        </div>
what's about related articles block?

2019-07-28 00:00 UTC, Drapegnik commented
![](https://github.trello.services/images/mini-trello-icon.png) [admin: articles page](https://trello.com/c/I1v3J11m/369-admin-articles-page)

2019-07-31 15:28 UTC, Drapegnik requested changes
and, please, fix lint errors

2019-07-31 15:28 UTC, Drapegnik commented on constants/social.js
> +    icon: 'odnoklassniki',
redundant

2019-08-02 20:47 UTC, Drapegnik approved these changes

2019-08-02 20:52 UTC, andemerie commented
![](https://github.trello.services/images/mini-trello-icon.png) [article page frontend](https://trello.com/c/uTQAYI3T/379-article-page-frontend)

2019-08-02 20:53 UTC, merged