[WIP] Cards and Blocks
babajka/babajka-frontend pull request #80
Opened 2019-10-19 17:17 UTC by UladBohdan

* Proper border radius for Tag Cards within the Block

2019-10-19 17:17 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [to fix border-radius for TagByTopic block](https://trello.com/c/FuJyEtu9/442-to-fix-border-radius-for-tagbytopic-block)

2019-10-19 19:13 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Card Border](https://trello.com/c/tXxQhA63/444-card-border)

2019-10-22 12:20 UTC, Drapegnik commented on components/articles/cards/CardWrapper.js
> +        'theme-black': colorLooksBlack(color),
maybe add comment here, to explain logic / connection to design?

2019-10-22 12:23 UTC, Drapegnik requested changes

2019-10-22 12:23 UTC, Drapegnik commented on utils/ui.js
> +import every from 'lodash/every';
`Array.every`

2019-10-22 12:23 UTC, Drapegnik commented on utils/ui.js
> +    .replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i, (m, r, g, b) => `#${r}${r}${g}${g}${b}${b}`)
Please extract regex to constant & add link to https://regex101.com

2019-10-22 12:25 UTC, Drapegnik commented on utils/ui.js
> +    .replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i, (m, r, g, b) => `#${r}${r}${g}${g}${b}${b}`)
for example: https://github.com/babajka/babajka-backend/blob/develop/src/services/fibery/utils.js#L14-L15

2019-10-22 15:16 UTC, Drapegnik approved these changes

2019-10-22 20:07 UTC, merged