Post-launch fixes
babajka/babajka-frontend pull request #92
Opened 2020-01-28 13:03 UTC by UladBohdan

2020-01-28 13:05 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [remove "article" type from metadata for /about and possibly other pages](https://trello.com/c/H2D2Ph4J/476-remove-article-type-from-metadata-for-about-and-possibly-other-pages)

2020-01-28 14:45 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [diary share bugs](https://trello.com/c/AUbLQdq2/478-diary-share-bugs)

2020-01-29 16:39 UTC, Drapegnik commented on components/social/ShareButtons.js
> +  text: {
```js
PropTypes.shape({
     basic: PropTypes.string.isRequired,
     extended: PropTypes.string,
}).isRequired
```

2020-01-29 16:39 UTC, Drapegnik commented on components/social/ShareButtons.js
> +  text: {
remove

2020-01-29 16:40 UTC, Drapegnik requested changes

2020-01-29 16:40 UTC, Drapegnik commented on pages/diary.js
> +      <MetaDescription description={`${fiberyToString(content).substring(0, 150)}...`} />
extract to constant

2020-01-29 16:40 UTC, Drapegnik commented on pages/diary.js
> +            text={getShareText(date, name, lang, fiberyToString(content).substring(0, 140))}
same as above

2020-01-29 18:07 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [to implement Web Share API for mobile browsers](https://trello.com/c/aFghFllw/472-to-implement-web-share-api-for-mobile-browsers)

2020-01-29 18:08 UTC, UladBohdan commented
![](https://github.trello.services/images/mini-trello-icon.png) [social share open app on mobile](https://trello.com/c/vgfV3w7E/470-social-share-open-app-on-mobile)

2020-01-29 22:30 UTC, Drapegnik requested changes

2020-01-29 22:30 UTC, Drapegnik commented on components/articles/Article.js
> +          <ShareButtons urlPath={router.asPath} text={{ basic: title }} />
it better (due to performance reason) to pass text directly, nor as object:
```jsx
<ShareButtons basic={title} />
```

2020-01-29 22:30 UTC, Drapegnik commented on components/social/ShareButtons.js
> +const ShareButtons = ({ urlPath, text: { basic, extended } }) => {
```suggestion
const ShareButtons = ({ urlPath, basic, extended }) => {
```

2020-01-29 22:30 UTC, Drapegnik commented on components/social/ShareButtons.js
> +            if (navigator.share) {
could you check for it in top of component render?
```jsx
if (navigator.share) {
   return <Button onClick={navigator. ... />
}

return <ButtonGroup
```

2020-01-31 11:57 UTC, Drapegnik submitted a review, later dismissed

2020-01-31 14:50 UTC, Drapegnik approved these changes

2020-01-31 15:00 UTC, merged